import type { Lesson } from "./types.ts";
import { sanitizeLesson } from "./sanitizer.ts";
import { ledgerEntities } from "./ledger.ts";

export function normalizeText(text: string): string {
  return text.normalize("NFC").toLowerCase().replace(/\s+/g, " ").trim();
}

export function appendLesson(
  existing: Lesson[],
  lesson: Lesson,
): { lessons: Lesson[]; action: "added" | "duplicate" } {
  const key = normalizeText(lesson.text);
  if (existing.some((l) => normalizeText(l.text) === key)) {
    return { lessons: existing, action: "duplicate" };
  }
  return { lessons: [...existing, lesson], action: "added" };
}

export function sameTopic(lessons: Lesson[], topic: string): Lesson[] {
  return lessons.filter((l) => l.status === "accepted" && l.topic === topic);
}

export function renderHotMemory(
  lessons: Lesson[],
  opts: { maxLines?: number } = {},
): { hot: string; overflow: Lesson[]; excluded: Lesson[] } {
  const maxLines = opts.maxLines ?? 100;
  // Re-run the ethical wall at render (Fix 2): a lesson clean when accepted can
  // become contaminated once a later proposal adds a new matter-party entity to
  // the ledger. Screen every accepted lesson against the full ledger-known
  // entity set; failures are EXCLUDED from the HOT body and surfaced with a
  // visible marker — never silently dropped.
  const entities = ledgerEntities(lessons);
  const accepted = lessons
    .filter((l) => l.status === "accepted")
    .slice()
    .sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1)); // newest first
  const sane: Lesson[] = [];
  const excluded: Lesson[] = [];
  for (const l of accepted) {
    if (sanitizeLesson(l.text, entities).ok) sane.push(l);
    else excluded.push(l);
  }
  const header = [
    "# Firm Memory (HOT)",
    "",
    "<!-- generated by the learning loop; edit lessons via the approval flow -->",
    "",
  ];
  const marker = excluded.length
    ? [`<!-- excluded: ${excluded.length} lessons failed sanitization -->`, ""]
    : [];
  const kept: string[] = [];
  const overflow: Lesson[] = [];
  let lineCount = header.length + marker.length + 1; // +1 for the trailing line below
  for (const l of sane) {
    if (lineCount + 1 > maxLines) {
      overflow.push(l);
      continue;
    }
    kept.push(`- (${l.topic}) ${l.text}`);
    lineCount += 1;
  }
  return { hot: [...header, ...marker, ...kept, ""].join("\n"), overflow, excluded };
}
