import type { Lesson } from "./types.ts";

export function normalizeText(text: string): string {
  return text.normalize("NFC").toLowerCase().replace(/\s+/g, " ").trim();
}

export function appendLesson(
  existing: Lesson[],
  lesson: Lesson,
): { lessons: Lesson[]; action: "added" | "duplicate" } {
  const key = normalizeText(lesson.text);
  if (existing.some((l) => normalizeText(l.text) === key)) {
    return { lessons: existing, action: "duplicate" };
  }
  return { lessons: [...existing, lesson], action: "added" };
}

export function sameTopic(lessons: Lesson[], topic: string): Lesson[] {
  return lessons.filter((l) => l.status === "accepted" && l.topic === topic);
}

export function renderHotMemory(
  lessons: Lesson[],
  opts: { maxLines?: number } = {},
): { hot: string; overflow: Lesson[] } {
  const maxLines = opts.maxLines ?? 100;
  const accepted = lessons
    .filter((l) => l.status === "accepted")
    .slice()
    .sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1)); // newest first
  const header = [
    "# Firm Memory (HOT)",
    "",
    "<!-- generated by the learning loop; edit lessons via the approval flow -->",
    "",
  ];
  const kept: string[] = [];
  const overflow: Lesson[] = [];
  let lineCount = header.length + 1; // +1 for the trailing line below
  for (const l of accepted) {
    if (lineCount + 1 > maxLines) {
      overflow.push(l);
      continue;
    }
    kept.push(`- (${l.topic}) ${l.text}`);
    lineCount += 1;
  }
  return { hot: [...header, ...kept, ""].join("\n"), overflow };
}
